import {NextIntlClientProvider, hasLocale} from 'next-intl'
import {notFound} from 'next/navigation'
import type {Metadata} from 'next'

import './globals.css'
import {routing} from '@/src/i18n/routing'
import LenisProvider from '@/src/provider/LenisProvider'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

interface RootLayoutProps {
  children: React.ReactNode
  params: Promise<{locale: string}>
}

export default async function RootLayout({children, params}: Readonly<RootLayoutProps>) {
  // Ensure that the incoming `locale` is valid
  const {locale} = await params
  if (!hasLocale(routing.locales, locale)) {
    notFound()
  }

  return (
    <html
      lang={locale}
      suppressHydrationWarning
    >
      <NextIntlClientProvider>
        <LenisProvider>
          <body>{children}</body>
        </LenisProvider>
      </NextIntlClientProvider>
    </html>
  )
}
